SET DJANGO_SUPERUSER_USERNAME=admin
SET DJANGO_SUPERUSER_PASSWORD=admin
SET DJANGO_SUPERUSER_EMAIL=mkisunko@gmail.com 
ECHO %DJANGO_SUPERUSER_USERNAME%
ECHO %DJANGO_SUPERUSER_PASSWORD%
ECHO %DJANGO_SUPERUSER_EMAIL%
